name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sqrereadonly
          password: ${{ secrets.DOCKERHUB_SQREREADONLY_TOKEN }}

      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --extra-download Poster.pdf --pdf DMTN-287.pdf --ltd-product dmtn-287 --lsstdoc "DMTN-287.tex" --author "William O'Mullane" --author "Yusra AlSayyad" --author "James Chiang" --author "Richard Dubois" --author "Frossie Economou" --author "Fabio Hernandez" --author "Flora Huang" --author "Tim Jenness" --author "Kian-Tat Lim" --author "Yee-Ting Li" --author "Fritz Mueller" --author "Dan Speck" --author "Stephen Pietrowicz" --author "Wei Yang" --abstract "Cloud computing offers unparalleled flexibility, a constantly increasing set of 'Infrastructure As A Service' capabilities, resource elasticity and security isolation. One of the most significant barriers in astronomy to wholesale adoption of cloud infrastructures is the cost for hot storage of large datasets - particularly for Rubin, a Big Data project sized at 0.5 Exabytes (500 Petabytes) over the duration of its 10-year mission. We are planning to reconcile this with a “hybrid” model where user-facing services are deployed on Google Cloud with the majority of data holdings residing in our on-premises Data Facility at SLAC. We discuss the opportunities, status, risks, and technical challenges  of this approach."
